name: Generate GitHub Snake Animation

on:
  schedule:
    - cron: "0 0 * * *"  # Runs every night
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Generate GitHub Snake SVG
        uses: Platane/snk@master
        with:
          github_user_name: Dealer-09
          outputs: |
            dist/github-snake.svg?color_snake=#40a2ff
            dist/github-snake-dark.svg?color_snake=#40a2ff&color_dots=#0d1117,#161b22,#010409

      - name: Push to output branch
        uses: crazy-max/ghaction-github-pages@v3
        with:
          target_branch: output
          build_dir: dist
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
